### ISSUE TITLE
Today screensaver

### ISSUE THREAD

**Issue by gingerbeardman** [aharris88/awesome-osx-screensavers#6]
### Today

> Inspired by On Kawara's "Today Series". An ongoing work of more than 2000 paintings, each consisting of a monochrome background onto which is inscribed the date of the day on which the individual painting is executed, in the language and according to the calendrical conventions of the country in which Kawara is present when he begins it.

FREE

[![](http://www.gingerbeardman.com/today/today.png)](http://www.gingerbeardman.com/today/)

ps: I made this

**Comment by aharris88** [comment]
I tried it out. Does it ever change or does it just show the current date on a random background color?

If it doesn't ever change, then I probably won't add it, because I expect screensavers to have some sort of change or animation.

**Comment by gingerbeardman** [comment]
Fair point. This one stays on the options you've chosen (date, time, day) with/without random colour.

Also, I don't think modern displays require screensavers at all, as they're not susceptible to burn-in.

**Comment by aharris88** [comment]
Yeah that's true, it just threw me off when it didn't change. I'm going to leave this open and reconsider it later. I wasn't familiar with Kawara's "Today Series". Maybe if I had heard of it before, I would think that this is more awesome.

**Comment by gingerbeardman** [comment]
Haha! I think it's just some nice modern art. And art is a very personal thing when it comes to taste! I think it's nice, peaceful, but I'm sure some people will hate it :)

**Comment by aharris88** [comment]
Yeah, I looked it up and I like how it has a newspaper for every date.
